/* eslint-disable */
/**
 * const prefixCls = 'style-632484';
 * const images = '/static/images/src/bbs/Article';
 * @Author: czy0729
 * @Date: 2018-07-11 17:28:19
 * @Last Modified by: czy0729
 * @Last Modified time: 2018-07-12 16:22:48
 * @Path m.benting.com.cn /src/bbs/Article/mock.js
 */
export const mockDetail = {
  _loaded: true,
  content:
    '<p>馈以百万！感恩有你！亲爱的各位汀友粉丝拥趸们，还有1个月即将迎来本汀旗舰店登陆天猫四周年纪念日！这是所有汀粉们的节日，因为你们，才有本汀旗舰店的今日！四年不易，未来更艰！但你们的喜爱拥护支持是支撑我们勇往直前，无畏风雨的无限动力！所以就在7月28日，我们将举办[7.28一万支本汀鱼竿粉丝大馈赠]感恩庆典，获得资格后仅需20元运费即可拥有2018本汀最新台钓力作，以此答谢一路以来支持我们的汀友们！</p>\n<p><br></p>\n<p><strong>本次庆典针对所有购买过本汀天猫旗舰店的用户，您只需：</strong></p>\n<p><br>\n1、所有自本汀天猫旗舰店开业购买过本汀任何产品的汀友将购买的旺旺ID报名提交即可！</p>\n<p><br>\n2、还没有在本汀天猫旗舰店购买过本汀产品的汀友在7月27日以前将购买价值100元（包含）以上本汀产品以及确认收货的旺旺ID报名提交即可！</p>\n<p><br>\n本次回馈的作品为本汀2018最新款台钓力作：天弧斩月刀-鲤！作品将于7月28日首发开放给通过活动的汀友购买，其中十二尺800支、十三尺800支、十五尺2900支、十六尺1000支、十八尺2900支、十九尺800支、廿一尺600支、廿四尺200支，共10000支！</p>\n<p><br>\n<strong>注意事项：</strong><br>\n1、先来后到，先报名先审核先通过，达到1万个合格名额即封贴，没有达到上述数量也将一支不少诚意奉上！如有给过恶意差评审核人员将有权不通过！</p>\n<p><br>\n2、因不能保证所有人都能抢到心仪的尺寸，所以鱼竿太多的汀友请把机会让给有需要的人，如发生占用资源却又不拍将会被全网拉黑，以后将无法享有本汀的任何优惠及福利！</p>\n<p><br>\n3、回馈采用发放答谢金到购买汀友的银行账户的形式，所以报名没有通过的用户请不要拍，否则将无法获得返款！因此产生的退货或货品损坏以及纠纷等费用后果将自行承担！</p>\n<p><br>\n4、庆典开始时间为7月28日上午十点，购买后请在本帖填写订单号和收返款的银行卡账号，收到货评论后我们会在实付金额扣除20元运费后发放答谢金！</p>\n<p><br>\n5、灵动、本汀官网级别高或老会员、VIP收到返款的时间为3个工作日左右，但为避免有不法分子在收到返款后利用7天无理由退换货规则骗取钱财，低级别的会员收到返款的时间为10个工作日左右。</p>\n<p><br>\n6、本活动感恩回馈力度之大真心实意看得见，20元甚至不够包装仓储物流打包耗材天猫佣金等费用！如果在评论中出现20元买或卖鱼竿，或者因没有抢到合适尺寸等原因发泄怨气给予不中肯评论等将会影响款项发放！</p>\n<p><br>\n7、本次活动鱼竿均有售后保障！但需要支付一定的成本费用。</p>\n<p><br>\nOK！活动要圆满，规则必先行！以上注意事项还请汀友们理解！四年风雨同舟，本汀因你精彩！[7.28一万支本汀鱼竿粉丝大馈赠]感恩庆典报名现正式开始！</p>\n<p><br></p>\n<p><strong>请使用手机端直接在本帖下方进行报名即可↓↓↓ （如果没看到报名按钮，请</strong><a>点击这里跳转</a><strong>）</strong></p>\n<p><br></p>',
  createTime: '1531281598',
  displayState: '3',
  ensNum: '71',
  faceImg: '203589',
  fanAuth: '2',
  forumId: '75',
  grade: '5',
  guessingData: '',
  isCommentDisplay: '1',
  isRegistration: '1',
  json:
    '{"entityMap":{"0":{"type":"link","mutability":"IMMUTABLE","data":{"link":"https://www.tw-bt.com/bbs/article/93792","tag":"点击这里跳转"}}},"blocks":[{"key":"clv75","text":"馈以百万！感恩有你！亲爱的各位汀友粉丝拥趸们，还有1个月即将迎来本汀旗舰店登陆天猫四周年纪念日！这是所有汀粉们的节日，因为你们，才有本汀旗舰店的今日！四年不易，未来更艰！但你们的喜爱拥护支持是支撑我们勇往直前，无畏风雨的无限动力！所以就在7月28日，我们将举办[7.28一万支本汀鱼竿粉丝大馈赠]感恩庆典，获得资格后仅需20元运费即可拥有2018本汀最新台钓力作，以此答谢一路以来支持我们的汀友们！","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"1cnqu","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"d4dt","text":"本次庆典针对所有购买过本汀天猫旗舰店的用户，您只需：","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":26,"style":"BOLD"}],"entityRanges":[],"data":{}},{"key":"ftj1b","text":"\\n1、所有自本汀天猫旗舰店开业购买过本汀任何产品的汀友将购买的旺旺ID报名提交即可！","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"5h4ut","text":"\\n2、还没有在本汀天猫旗舰店购买过本汀产品的汀友在7月27日以前将购买价值100元（包含）以上本汀产品以及确认收货的旺旺ID报名提交即可！","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"dlpf1","text":"\\n本次回馈的作品为本汀2018最新款台钓力作：天弧斩月刀-鲤！作品将于7月28日首发开放给通过活动的汀友购买，其中十二尺800支、十三尺800支、十五尺2900支、十六尺1000支、十八尺2900支、十九尺800支、廿一尺600支、廿四尺200支，共10000支！","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"5f7uf","text":"\\n注意事项：\\n1、先来后到，先报名先审核先通过，达到1万个合格名额即封贴，没有达到上述数量也将一支不少诚意奉上！如有给过恶意差评审核人员将有权不通过！","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":1,"length":5,"style":"BOLD"}],"entityRanges":[],"data":{}},{"key":"885du","text":"\\n2、因不能保证所有人都能抢到心仪的尺寸，所以鱼竿太多的汀友请把机会让给有需要的人，如发生占用资源却又不拍将会被全网拉黑，以后将无法享有本汀的任何优惠及福利！","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"93ej8","text":"\\n3、回馈采用发放答谢金到购买汀友的银行账户的形式，所以报名没有通过的用户请不要拍，否则将无法获得返款！因此产生的退货或货品损坏以及纠纷等费用后果将自行承担！","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"e2usr","text":"\\n4、庆典开始时间为7月28日上午十点，购买后请在本帖填写订单号和收返款的银行卡账号，收到货评论后我们会在实付金额扣除20元运费后发放答谢金！","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"8pstn","text":"\\n5、灵动、本汀官网级别高或老会员、VIP收到返款的时间为3个工作日左右，但为避免有不法分子在收到返款后利用7天无理由退换货规则骗取钱财，低级别的会员收到返款的时间为10个工作日左右。","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"839l9","text":"\\n6、本活动感恩回馈力度之大真心实意看得见，20元甚至不够包装仓储物流打包耗材天猫佣金等费用！如果在评论中出现20元买或卖鱼竿，或者因没有抢到合适尺寸等原因发泄怨气给予不中肯评论等将会影响款项发放！","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"170sn","text":"\\n7、本次活动鱼竿均有售后保障！但需要支付一定的成本费用。","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"ccf7c","text":"\\nOK！活动要圆满，规则必先行！以上注意事项还请汀友们理解！四年风雨同舟，本汀因你精彩！[7.28一万支本汀鱼竿粉丝大馈赠]感恩庆典报名现正式开始！","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"48np1","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}},{"key":"7mfmr","text":"请使用手机端直接在本帖下方进行报名即可↓↓↓ （如果没看到报名按钮，请点击这里跳转）","type":"unstyled","depth":0,"inlineStyleRanges":[{"offset":0,"length":35,"style":"BOLD"},{"offset":41,"length":1,"style":"BOLD"}],"entityRanges":[{"offset":35,"length":6,"key":0}],"data":{}},{"key":"5i4v8","text":"","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}]}',
  likeAdd: '102',
  likeSub: '0',
  niname: '社区管理员',
  postId: '2181728',
  replyNum: '2626',
  role: '',
  tag: '',
  threadId: '93792',
  title: '[7.28一万支本汀鱼竿粉丝大馈赠]感恩庆典！',
  userId: '4587152172004623',
  userSource: '1',
  viewNum: '14658',
  vip: '0',
  registrationData: {
    id: '35',
    thread_id: '93792',
    status: '1',
    num: '10000',
    has_order: '0',
    start_time: '1531281600',
    end_time: '1532743200',
    created_time: '1531281601',
    pass_num: '10000',
    registration_end_time: '1533441472',
    passNum: '10000',
    successNum: 0,
    joinNum: 2241
  }
};

export const mockComment = {
  list: [
    {
      postId: '3144953',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383653',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9022',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4715859360350993',
      niname: '灵动3098',
      faceImg: '312791',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144947',
      threadId: '93792',
      content: '分享到QQ群里了',
      createTime: '1531383616',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9021',
      parentId: '0',
      commentImg: '313853',
      rtype: '0',
      userId: '4715976061950147',
      niname: '帅的人先上鱼',
      faceImg: '313836',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144946',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383608',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9020',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4578387535813898',
      niname: '威廉一号',
      faceImg: 'static/uploads/png/20170519/591e5f9e2c2bc.png',
      role: '0',
      grade: '2',
      vip: '0',
      fanAuth: '2',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144945',
      threadId: '93792',
      content: '报名',
      createTime: '1531383594',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9019',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4715970758925323',
      niname: '灵动3579三十',
      faceImg: 'static/uploads/png/20170519/591e5f9e2c2bc.png',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144941',
      threadId: '93792',
      content: '报名成功',
      createTime: '1531383562',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9018',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4698600514370462',
      niname: '灵动7217',
      faceImg: 'static/uploads/png/20170519/591e5f9e2c2bc.png',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144940',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383560',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9017',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4715970758925323',
      niname: '灵动3579三十',
      faceImg: 'static/uploads/png/20170519/591e5f9e2c2bc.png',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144938',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383547',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9016',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4698600514370462',
      niname: '灵动7217',
      faceImg: 'static/uploads/png/20170519/591e5f9e2c2bc.png',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144937',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383545',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9015',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4715976061950147',
      niname: '帅的人先上鱼',
      faceImg: '313836',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144936',
      threadId: '93792',
      content: '我想买一支',
      createTime: '1531383529',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9014',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4715667695953720',
      niname: '有你我幸福',
      faceImg: '311095',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144935',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383523',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9013',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4706139321473380',
      niname: '灵动9391',
      faceImg: 'static/uploads/png/20170519/591e5f9e2c2bc.png',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144934',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383522',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9012',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '21520',
      niname: '赌爱',
      faceImg: 'static/uploads/png/20170519/591e5f9e2c2bc.png',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '2',
      userSource: '3',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144933',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383505',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9011',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4670271927972544',
      niname: '灵动6123',
      faceImg: 'static/uploads/png/20170519/591e5f9e2c2bc.png',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '2',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144932',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383503',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9010',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4591808611816215',
      niname: '快乐钓鱼时光',
      faceImg: '31529',
      role: '0',
      grade: '7',
      vip: '1',
      fanAuth: '2',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144930',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383482',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9009',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4578544619472132',
      niname: '挚爱本汀',
      faceImg: '5416',
      role: '0',
      grade: '3',
      vip: '0',
      fanAuth: '2',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144927',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383457',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9008',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4715976210021959',
      niname: '蓝雨蓝莓',
      faceImg: 'static/uploads/png/20170519/591e5f9e2c2bc.png',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    },
    {
      postId: '3144926',
      threadId: '93792',
      content: '#已报名#',
      createTime: '1531383448',
      isDisable: '0',
      isFirst: '0',
      json: '',
      top: '0',
      floor: '9007',
      parentId: '0',
      commentImg: '',
      rtype: '0',
      userId: '4706162692305057',
      niname: '灵动2808',
      faceImg: 'static/uploads/png/20170519/591e5f9e2c2bc.png',
      role: '0',
      grade: '1',
      vip: '0',
      fanAuth: '',
      userSource: '1',
      parUserId: '0',
      parNiname: '',
      parFaceImg: '',
      parvip: '',
      isCommentDisplay: '1',
      parCreateTime: '',
      parMessage: ''
    }
  ],
  pageinfo: { recordtotal: 9021, pagetotal: 1128, page: 2, limit: 8 },
  _loaded: true,
  _hasMore: true,
  _query: {
    _: {
      page: 2,
      limit: 8,
      order: { top: 'desc', createTime: 'desc' },
      search: { threadId: '93792' }
    }
  },
  _timestamp: 1531383639
};
